#!/usr/bin/env python3
"""Check Context Layer database, migrations, embeddings, and MCP stdio."""

import argparse
import asyncio
import json
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from context_layer.env import load_local_env

load_local_env(ROOT / ".env")

DEFAULT_ENV = {
    "SURREAL_URL": "ws://127.0.0.1:8010",
    "SURREAL_NS": "dev",
    "SURREAL_DB": "context_layer",
    "SURREAL_USER": "root",
    "SURREAL_PASS": "",
}
EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"  # Keep in sync with context_layer/core.py.
MIGRATIONS_DIR = ROOT / "sql" / "migrations"


def _load_server_config() -> tuple[str, list[str], Path, dict[str, str], str]:
    """Resolve the same stdio command/environment generated by setup_mcp.py."""
    config_path = ROOT / ".mcp" / "config.json"
    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
        server = config["server"]
        command = str(server["command"])
        if not Path(command).is_absolute():
            command = str((ROOT / command).resolve())
        args = [str(arg) for arg in server.get("args", ["mcp_server.py"])]
        cwd = Path(server.get("cwd") or ROOT).expanduser().resolve()
        env = os.environ.copy()
        env.update({str(k): str(v) for k, v in server.get("env", {}).items()})
        return command, args, cwd, env, f"loaded {config_path.relative_to(ROOT)}"
    except (OSError, json.JSONDecodeError, KeyError, TypeError) as exc:
        env = os.environ.copy()
        return (
            sys.executable,
            [str(ROOT / "mcp_server.py")],
            ROOT,
            env,
            f"using launcher defaults (.mcp/config.json unavailable: {exc})",
        )


def _result(name: str, status: str, detail: str, fix: str | None = None) -> dict[str, str]:
    record = {"name": name, "status": status, "detail": detail}
    if fix:
        record["action"] = fix
    return record


async def _connect_db(env: dict[str, str]):
    from surrealdb import AsyncSurreal

    db = AsyncSurreal(env.get("SURREAL_URL", DEFAULT_ENV["SURREAL_URL"]))
    await db.connect()
    await db.signin({
        "username": env.get("SURREAL_USER", DEFAULT_ENV["SURREAL_USER"]),
        "password": env.get("SURREAL_PASS", DEFAULT_ENV["SURREAL_PASS"]),
    })
    await db.use(
        env.get("SURREAL_NS", DEFAULT_ENV["SURREAL_NS"]),
        env.get("SURREAL_DB", DEFAULT_ENV["SURREAL_DB"]),
    )
    await db.query("INFO FOR DB;")
    return db


async def _check_database_and_migrations(env: dict[str, str]) -> tuple[dict, dict]:
    try:
        db = await _connect_db(env)
    except Exception as exc:
        failed = _result(
            "Database",
            "NOT READY",
            f"Could not connect to {env.get('SURREAL_URL', DEFAULT_ENV['SURREAL_URL'])}: {type(exc).__name__}: {exc}",
            "Start SurrealDB and check SURREAL_URL, namespace, database, and credentials.",
        )
        return failed, _result("Migrations", "BLOCKED", "Skipped because the database connection failed.")

    db_status = _result(
        "Database",
        "READY",
        "SurrealDB connection, authentication, namespace, database, and INFO query succeeded.",
    )
    try:
        result = await db.query("SELECT version FROM schema_version ORDER BY version;")
        applied = {
            int(row["version"])
            for row in (result[0] if result and isinstance(result[0], list) else [])
            if isinstance(row, dict) and row.get("version") is not None
        }
    except Exception as exc:
        migrations_status = _result(
            "Migrations",
            "NOT READY",
            f"Could not read schema_version: {type(exc).__name__}: {exc}",
            "Run python mcp_server.py to apply the initial schema and pending migrations.",
        )
    else:
        migration_files = sorted(MIGRATIONS_DIR.glob("*.surql"))
        versions: dict[int, str] = {}
        invalid_files: list[str] = []
        for path in migration_files:
            match = re.fullmatch(r"(\d{4})_(.+)\.surql", path.name)
            if not match:
                invalid_files.append(path.name)
                continue
            version = int(match.group(1))
            if version in versions:
                invalid_files.append(f"duplicate version {version:04d}")
            versions[version] = path.name

        pending = sorted(set(versions) - applied)
        unknown_applied = sorted(applied - set(versions))
        if not migration_files or invalid_files or pending or unknown_applied:
            parts = []
            if not migration_files:
                parts.append("no migration files found")
            if invalid_files:
                parts.append("invalid migration files: " + ", ".join(invalid_files))
            if pending:
                parts.append("pending: " + ", ".join(f"{v:04d}" for v in pending))
            if unknown_applied:
                parts.append("database contains versions absent from this checkout: "
                             + ", ".join(f"{v:04d}" for v in unknown_applied))
            migrations_status = _result(
                "Migrations",
                "NOT READY",
                "; ".join(parts),
                "Review sql/migrations/README.md, then run python mcp_server.py to apply pending migrations.",
            )
        else:
            migrations_status = _result(
                "Migrations",
                "READY",
                f"All {len(versions)} migration(s) are applied: "
                + ", ".join(f"{v:04d}" for v in sorted(versions)) + ".",
            )

    await db.close()
    return db_status, migrations_status


def _check_embedding(python_executable: str, timeout: int, download_model: bool, env: dict[str, str]) -> dict:
    local_only = not download_model
    probe_code = (
        "import json; "
        "from fastembed import TextEmbedding; "
        f"model = TextEmbedding(model_name={EMBEDDING_MODEL!r}, local_files_only={local_only!r}); "
        "vector = next(model.embed(['context layer readiness check'])); "
        "print(json.dumps({'dimensions': len(vector)}))"
    )
    try:
        probe = subprocess.run(
            [python_executable, "-c", probe_code],
            cwd=ROOT,
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired:
        return _result(
            "Embedding model",
            "NOT READY",
            f"A local embedding probe exceeded the {timeout}s timeout.",
            "Check available memory/CPU, or rerun with a larger --timeout value.",
        )

    if probe.returncode == 0:
        try:
            details = json.loads(probe.stdout.strip().splitlines()[-1])
            dimensions = details["dimensions"]
        except (IndexError, json.JSONDecodeError, KeyError, TypeError):
            dimensions = "unknown"
        return _result(
            "Embedding model",
            "READY",
            f"{EMBEDDING_MODEL} produced an embedding ({dimensions} dimensions).",
        )

    error = (probe.stderr or probe.stdout).strip().splitlines()
    explanation = error[-1][:500] if error else f"probe exited with code {probe.returncode}"
    if download_model:
        action = "Check network access and rerun python scripts/diagnostics.py --download-model."
    else:
        action = (
            "The model is not cached locally. Run python scripts/diagnostics.py --download-model "
            "once while online, then rerun diagnostics."
        )
    return _result("Embedding model", "NOT READY", explanation, action)


async def _read_mcp_response(proc: asyncio.subprocess.Process, request_id: int, timeout: int) -> dict:
    if proc.stdout is None:
        raise RuntimeError("MCP process has no stdout pipe")
    while True:
        line = await asyncio.wait_for(proc.stdout.readline(), timeout=timeout)
        if not line:
            raise RuntimeError(f"MCP process exited before response (exit code {proc.returncode})")
        try:
            message = json.loads(line.decode("utf-8"))
        except (UnicodeDecodeError, json.JSONDecodeError):
            # Ignore startup text so the diagnostic can still surface a useful
            # protocol result; a production stdio server should keep stdout clean.
            continue
        if isinstance(message, dict) and message.get("id") == request_id:
            if "error" in message:
                raise RuntimeError(f"MCP returned an error: {message['error']}")
            return message


async def _check_mcp(command: str, args: list[str], cwd: Path, env: dict[str, str], timeout: int) -> dict:
    proc = None
    try:
        proc = await asyncio.create_subprocess_exec(
            command,
            *args,
            cwd=str(cwd),
            env=env,
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.DEVNULL,
        )
        if proc.stdin is None:
            raise RuntimeError("MCP process has no stdin pipe")

        def send(message: dict) -> None:
            proc.stdin.write((json.dumps(message) + "\n").encode("utf-8"))

        send({
            "jsonrpc": "2.0",
            "id": 1,
            "method": "initialize",
            "params": {
                "protocolVersion": "2025-03-26",
                "capabilities": {},
                "clientInfo": {"name": "context-layer-diagnostics", "version": "1.0"},
            },
        })
        await proc.stdin.drain()
        initialize = await _read_mcp_response(proc, 1, timeout)
        if not isinstance(initialize.get("result"), dict):
            raise RuntimeError("MCP initialize response did not contain a result")

        send({"jsonrpc": "2.0", "method": "notifications/initialized"})
        send({"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}})
        await proc.stdin.drain()
        listed = await _read_mcp_response(proc, 2, timeout)
        tools = listed.get("result", {}).get("tools", [])
        if not tools:
            raise RuntimeError("MCP connected, but tools/list returned no tools")
        return _result(
            "MCP stdio connection",
            "READY",
            f"Initialize handshake and tools/list succeeded ({len(tools)} tools).",
        )
    except Exception as exc:
        if isinstance(exc, PermissionError):
            detail = f"Could not launch the configured MCP process: {exc}"
            action = (
                "Check execute permissions for the command in .mcp/config.json. "
                "If running inside a restricted environment, run diagnostics from a normal terminal."
            )
        elif isinstance(exc, FileNotFoundError):
            detail = f"Configured MCP executable or working directory was not found: {exc}"
            action = "Check the command, arguments, and cwd in .mcp/config.json."
        elif isinstance(exc, asyncio.TimeoutError):
            detail = f"MCP did not complete its handshake within {timeout} seconds."
            action = "Run python start_mcp.py to inspect startup errors, or retry with --timeout 180."
        else:
            detail = f"{type(exc).__name__}: {exc}"
            action = "Run python start_mcp.py to inspect startup errors, then check .mcp/config.json."
        return _result(
            "MCP stdio connection",
            "NOT READY",
            detail,
            action,
        )
    finally:
        if proc is not None:
            if proc.stdin and not proc.stdin.is_closing():
                proc.stdin.close()
            if proc.returncode is None:
                try:
                    await asyncio.wait_for(proc.wait(), timeout=3)
                except asyncio.TimeoutError:
                    proc.terminate()
                    try:
                        await asyncio.wait_for(proc.wait(), timeout=3)
                    except asyncio.TimeoutError:
                        proc.kill()
                        await proc.wait()


def _print_report(checks: list[dict[str, str]], json_output: bool) -> None:
    if json_output:
        print(json.dumps({"ready": all(c["status"] == "READY" for c in checks), "checks": checks}, indent=2))
        return
    print("Context Layer readiness")
    print("=" * 25)
    for check in checks:
        print(f"[{check['status']}] {check['name']}: {check['detail']}")
        if check.get("action"):
            print(f"         Action: {check['action']}")
    if all(c["status"] == "READY" for c in checks):
        print("\nAll checks passed.")
    else:
        print("\nOne or more checks need attention.")


async def _run(args: argparse.Namespace) -> int:
    command, command_args, cwd, env, config_note = _load_server_config()
    print(f"MCP configuration: {config_note}") if not args.json else None

    database, migrations = await _check_database_and_migrations(env)
    embedding = _check_embedding(command, args.timeout, args.download_model, env)
    checks = [database, migrations, embedding]

    if all(c["status"] == "READY" for c in checks):
        mcp = await _check_mcp(command, command_args, cwd, env, args.timeout)
    else:
        mcp = _result(
            "MCP stdio connection",
            "BLOCKED",
            "Skipped because the database, migrations, or embedding model is not ready.",
        )
    checks.append(mcp)
    _print_report(checks, args.json)
    return 0 if all(c["status"] == "READY" for c in checks) else 1


def main() -> int:
    parser = argparse.ArgumentParser(description="Check Context Layer database, migrations, embeddings, and MCP readiness.")
    parser.add_argument(
        "--download-model",
        action="store_true",
        help="allow FastEmbed to download the local model if it is not cached (network required)",
    )
    parser.add_argument("--timeout", type=int, default=120, help="timeout in seconds for model and MCP probes (default: 120)")
    parser.add_argument("--json", action="store_true", help="print the result as JSON for scripts and support diagnostics")
    args = parser.parse_args()
    if args.timeout < 1:
        parser.error("--timeout must be greater than zero")
    try:
        return asyncio.run(_run(args))
    except KeyboardInterrupt:
        print("Diagnostics interrupted.", file=sys.stderr)
        return 130


if __name__ == "__main__":
    sys.exit(main())
